### ISSUE TITLE
CORS support for standalone running instance

### ISSUE THREAD

**Issue by victorskl** [umccr/htsget-rs#100]
Context:

- A low prior change request: To add direct CORS support for built-in servers for standalone run

Use Case:

- Local dev run with `cargo run -p htsget-http-actix` to use htsget-rs as backend in Pipeline development and/or Portal integration with IGV.js

Workaround:

- Use Nginx/Haproxy to handle CORS then reverse proxy to htsget-rs servers

Need Changes:

I guess, this should be quick -- 2 parts in there:
- `actix_cors` crate for actix-web for Ticket server
- activate `tower_http::cors` feature in tower/axum for built-in storage streaming server

**Comment by mmalenic** [comment]
Closed via #119

**Comment by mmalenic** [comment]
Closed via #119.
