### ISSUE TITLE
Consider multiple buckets support

### ISSUE THREAD

**Issue by victorskl** [umccr/htsget-rs#102]
Context:

- At the mo; htsget-rs support [single bucket configuration](https://github.com/umccr/htsget-rs/tree/40a9c93f8ae8a2bf4dc3142003e051ea73c50c6f/htsget-http-actix#environment-variables) as follows.

```
export HTSGET_S3_BUCKET=my-primary-data
```

Desirable:

- It would be good; if we can configure it to multiple buckets as data may sparsely located across multiple locations/buckets

Related:

- This may also related to Htsget REST API endpoint resource ID mapping; currently is with regex pattern `.*` matching all keys under a bucket
- Hence, in-turn, this request indirectly refer to consider include bucket as part of its REST endpoint resource ID mapping
- i.e.

```
s3://my-bucket1/subject/key/to/data1.bam
s3://my-bucket2/another/subject/key/to/data1.bam
```

Then, Htsget REST endpoint resource ID will become

```
https://htsget-rs.my.org/my-bucket1/subject/key/to/data1.bam
https://htsget-rs.my.org/my-bucket2/another/subject/key/to/data1.bam

(or without extension suffix is fine)
https://htsget-rs.my.org/my-bucket1/subject/key/to/data1
https://htsget-rs.my.org/my-bucket2/another/subject/key/to/data1
```

Or, with htsget URI scheme (on-going discussion [#581](https://github.com/samtools/hts-specs/issues/581) https://github.com/umccr/data-portal-client/pull/88)

```
htsget://data.my.org/my-bucket1/subject/key/to/data1
htsget://data.my.org/my-bucket2/another/subject/key/to/data1
```

**Comment by brainstorm** [comment]
Thanks for opening this one, Victor, it taps into a related discussion in https://github.com/umccr/htsget-rs/pull/88#issuecomment-1148221436. If we implement this multi-storage backend feature we should also support multiple data sources **from within the same storage backend**, transparently.

/cc @mmalenic
