### ISSUE TITLE
Implement GA4GH's service-info endpoint

### ISSUE THREAD

**Issue by brainstorm** [umccr/htsget-rs#11]
According to the [htsget spec](https://samtools.github.io/hts-specs/htsget.html):

![Screen Shot 2021-04-09 at 9 43 01 pm](https://user-images.githubusercontent.com/175587/114174851-92a1be00-997c-11eb-9c67-05c8bdbacae8.png)

This service info endpoint can be modeled in:

https://github.com/chris-zen/htsget-mvp/blob/main/htsget-search/src/htsget/mod.rs

As part of the whole htsget request/response structs.

**Comment by chris-zen** [comment]
The service info endpoint is not a concern of the `htsget-search` crate. But the `HtsGet` trait can include a method to ask for capabilities, which can be used by the rest/http layer to fulfill the service info response.

**Comment by brainstorm** [comment]
@CastilloDel This should be a struct and endpoint callback away now that you are implementing the http side of htsget ;)

**Comment by CastilloDel** [comment]
Yes, it seems fairly easy. Probably better as a separate PR (?)
