### ISSUE TITLE
UMCCR prod deploy

### ISSUE THREAD

**Issue by brainstorm** [umccr/htsget-rs#125]
Essentially revisit the testing template that @victorskl provided over Slack so that we can substitute the current reference server implementation with this one.

**Comment by brainstorm** [comment]
Perhaps run compliance tests while we are at it: https://github.com/ga4gh/htsget-compliance

**Comment by brainstorm** [comment]
@mmalenic I take this is done as per https://github.com/umccr/htsget-rs/pull/133 being merged? :)

**Comment by mmalenic** [comment]
Yep, I think we can mark this as complete, because of #133 and https://github.com/umccr/infrastructure/issues/214.
