### ISSUE TITLE
Introduce another `StorageType` that can map any generic URL

### ISSUE THREAD

**Issue by mmalenic** [umccr/htsget-rs#134]
### Feature
Introduce a way for the ticket server to return tickets with any URL.

### Motivation
This would allow fetching htsget resources from anywhere, as currently the ticket server can only return tickets for a local data server or from AWS S3.

### Implementation
Add another `StorageType` that can format and resolve query ids to any URL.

**Comment by brainstorm** [comment]
Good discussion with @mmalenic over Slack, in summary:

1. We'll drop this feature as it introduces quite a bit of complexity and confusion over the storage backend vs external storage types being proposed here. Namely, even if an "external" storage type is defined, we'd need to implement its corresponding storage backend [(perhaps via OpenDAL which would provide a good router for different types of storage backends)](https://github.com/datafuselabs/opendal).
