### ISSUE TITLE
Providing the file size through the Storage abstraction

### ISSUE THREAD

**Issue by chris-zen** [umccr/htsget-rs#15]
For the BAM format, we need to know the size of the file to provide a close byte range for all the unplaced unmapped reads. The current alternative is to leave the end part open.

Possible names:

- `head`: which the HTTP verb you would use to get the size information (as well as other details like whether it exists or not) from S3
- `stats`: which is the metadata information you get for a file in unix
- `size`: more limited scope and focused on just getting the size.

We have two options for the result (where T will depend on the final semantics that we decide for this new method):

- `Result<Option<T>>`: Result encodes either a success or a failure, and the Option whether the file exists or not.
- `Result<T>`: Result encodes both success/failure and whether the file exists or not as one of the possible Error variants.

One possible example:

```rust
pub trait Storage {
  fn get<K: AsRef<str>>(&self, key: K, options: GetOptions) -> Result<PathBuf>;
  fn url<K: AsRef<str>>(&self, key: K, options: UrlOptions) -> Result<Url>;

  fn size<K: AsRef<str>>(&self, key: K) -> Result<usize>;
}
```

**Comment by brainstorm** [comment]
I'd go for head (stats can be confused with statistics and size is too limited, we might want/need more info from the file).

`Result<T>` looks shorter and more to the point, don't really see the need of the imbricated `Option` TBH.
