### ISSUE TITLE
Remove circular dependency involving htsget-test and htsget-search

### ISSUE THREAD

**Issue by mmalenic** [umccr/htsget-rs#158]
### Issue
The `htsget-test` crate has a circular dev dependency with `htsget-search`. This is resolved in cargo using feature flags to conditionally compile the code so that there is no circular dependency. Specifically, [`htsget-search`](https://github.com/umccr/htsget-rs/blob/aace176f4f265e3e9540cd696e70a7415c0c4c61/htsget-search/Cargo.toml#L51) depends on the `cors-tests` feature flag, but not the `server-tests` feature flag. We should consider remove this circular dependency entirely.

### Motivation
The circular dependency causes problems when deploying the crates, as `cargo publish` cannot easily resolve the circular dependency. See #153. It also might increase the understandability of the code, because the conditional compilation may not be easy to reason about.

### Implementation
The `htsget-test` crate can be split up into mutliple crates that contain only the required code to avoid a circular dependency. For example, `htsget-test` and `htsget-test-server`.

**Comment by brainstorm** [comment]
@mmalenic Instead of separating `htsget-test` into different crates, would it make sense to contain the minimum logic possible on the different crates so that they are self-contained and independent w.r.t testing?

**Comment by mmalenic** [comment]
Yes, that's probably the better approach. `htsget-test` does use some structs from `htsget-search`: https://github.com/umccr/htsget-rs/blob/0f64f48b9381de29309cfb6c398969b178d7187f/htsget-test/src/server_tests.rs#L14-L17 I'll see how easy it would be to remove these.
