### ISSUE TITLE
Support authenticated requests

### ISSUE THREAD

**Issue by dbampalikis** [umccr/htsget-rs#165]
**Short version** 
Possibility to use authorization header in the htsget request

**Longer Version**
The python client for htsget (https://github.com/ga4gh/htsget) and the samtools support the possibility of sending a JWToken when making a request against the htsget server. It would be great if the htsget server would be able to pass this header (and possibly any other headers the user is providing) to the backend that will be handling the request.

**Use case - Example scenario**
The htsget server is used for accessing data that requires authorization. One scenario to support that would be to have a service between the htsget server and an s3 backend, which passes the files to htsget. This middle layer could check the JWToken against some authority, access the file in the s3 backend and serve it to the htsget server.

**Comment by mmalenic** [comment]
When htsget-rs passes the authorization headers to the backend, what gets returned to htsget-rs? 
* Does htsget-rs just have access to the files already, and simply needs a confirmation of whether the user is authenticated or not?
* Is it the files themselves? I assume this wouldn't be the whole file, htsget-rs only needs the header and index to perform a search query. The backend would probably also need to be aware of the query id, in order to return the correct files?
* Another option could be to return an AWS S3 key and bucket, which htsget-rs is expected to fetch and has access to.

**Comment by dbampalikis** [comment]
The idea would be for the request to return exactly what it returns now. The proposed feature only enables for using an authentication service on the backend side (either on the S3 or as a service between the htsget server and the S3)

1. I guess that depends on the implementation. In our case, the service between the htsget server and the S3 backend is having access to the files, and through its endpoints, it provides access to the the htsget server, after authenticating and authoring the access. In general, I assume the authorization could happen either by a middle layer or by the S3 backend itself and they both require some kind of token for that?
2. I think that either the whole file or the header + the index file are possible. As long as there is a description of the expected format, it should be doable.
3. There are two issues here for our case: We are not using AWS S3 and we would like to avoid giving direct access from the htsget server to the storage, since it will be a user facing service

Does that make sense?

**Comment by mmalenic** [comment]
Yes it does. A few more clarifications/questions: 
1. What's the protocol htsget-rs would use with the external service? HTTP/TLS?
2. Would it be possible for the external service to return URLs containing the files (e.g. something similar to AWS presigned URLs) that htsget-rs could fetch? We think this would fit nicely with implemented a feature that allows htsget-rs to perform queries using any HTTP URL (see https://github.com/umccr/htsget-rs/issues/134). This would also disallow any direct access to the storage.
    * I was thinking that the service could return serialized [resolvers](https://github.com/umccr/htsget-rs/tree/main/htsget-config#resolvers). This would enable flexibility to choose which URLs/files correspond to the query id.

To illustrate this a bit more - the external service could return something like:
```toml
[[resolvers]]
regex = '.*'
substitution_string = '$0'

[resolvers.storage.url] # This would be a new storage type.
file = "https://data.umccr.org/example.bam"
index = "https://data.umccr.org/example.bam.bai"

# Could have multiple files here for one authorization header.

[resolvers.allow_guard]
allow_formats = ['BAM']
```
This does not need to be TOML, and it could instead be JSON or another format. These URLs would be fetched by htsget-rs while performing the query. A query would return a reference to the URLs in the resolvers:
```sh
curl -H "Authorization: <JWT_TOKEN>" "https://htsget.umccr.org/reads/example.bam"
```
```json
{
  "htsget": {
    "format": "BAM",
    "urls": [
      {
        "url": "https://data.umccr.org/example.bam",
        "headers": {
          "Range": "bytes=0-2596770"
        }
      },
      {
        "url": "data:;base64,H4sIBAAAAAAA/wYAQkMCABsAAwAAAAAAAAAAAA=="
      }
    ]
  }
}
```
The URL tickets returned by htsget-rs correspond to the URLs defined in the resolvers which htsget-rs got from the external service.
