### ISSUE TITLE
Add configurable endpoint for S3

### ISSUE THREAD

**Issue by mmalenic** [umccr/htsget-rs#169]
The AWS SDK allows setting an endpoint for the S3 service - which is useful for running it locally or with MinIO. This value cannot be automatically set from environment variables using [`aws_config::load_from_env()`](https://github.com/umccr/htsget-rs/blob/0cbc40388579458122d852c811924eded1384ce6/htsget-search/src/storage/aws.rs#L56), although this is an [open feature request](https://github.com/aws/aws-sdk/issues/229).

An `Option` should be added to [`S3Storage`](https://github.com/umccr/htsget-rs/blob/0cbc40388579458122d852c811924eded1384ce6/htsget-config/src/storage/s3.rs#L8-L10) which allows setting an AWS endpoint, that can be passed down to [`AWSS3Storage`](https://github.com/umccr/htsget-rs/blob/0cbc40388579458122d852c811924eded1384ce6/htsget-search/src/storage/aws.rs#L42-L45) and set with something like the S3 config builder [`set_endpoint_url`](https://docs.rs/aws-sdk-s3/0.26.0/aws_sdk_s3/config/struct.Builder.html#method.set_endpoint_url) function.

**Comment by brainstorm** [comment]
Implemented in https://github.com/umccr/htsget-rs/pull/171
