### ISSUE TITLE
More accurate byte ranges for BAM search results

### ISSUE THREAD

**Issue by chris-zen** [umccr/htsget-rs#17]
`VirtualPosition`'s encode the start of a BGZF block in it's high bits (known also as the compressed part or the coffset). When getting results from a BAI query with `noodles`, the ending `VirtualPosition`'s compressed value is pointing to the beginning of a block that might still include reads that need to be returned. If we want to translate that ending VirtualPosition into a byte offset in the file, we need to know where does that block finishes, but that's not something that the BAI index provides out of the box.

Our current solution is dummy and it just adds the maximum block size to the compressed part for the ending intervals to make sure that we don't loose any reads (at the expense of possibly adding many reads that don't belong to the sequence range that was queried)

A better alternative would be to construct a `HashMap<u64, u64>` from the BAI that would map the block starting offsets to the beginning of the closer contiguous block that we can infer from the BAI index. We could use that map to know the corresponding end for every compressed offset that we get for an end interval. In case that we don't find it in the map, we could fall back to the current strategy of adding the maximum block size.

To get that information from the BAI we can do something like:

```rust
  let index = bai::read(path.as_ref().with_extension("bam.bai"))?;
  
  let mut ref_seq_intervals: Vec<HashMap<u64, u64>> = Vec::with_capacity(index.reference_sequences().len());

  for (idx, idx_ref_seq) in index.reference_sequences().iter().enumerate() {
    if let Some(metadata) = idx_ref_seq.metadata() {
      let blocks: HashSet<u64> = idx_ref_seq
        .bins()
        .iter()
        .flat_map(|bin| bin.chunks().iter())
        .flat_map(|chunk| vec![chunk.start(), chunk.end()])
        .map(|vpos| vpos.compressed())
        .collect();
      let mut blocks: Vec<u64> = blocks.into_iter().collect();
      blocks.sort_unstable();

      let intervals: HashMap<u64, u64> = blocks
        .iter()
        .take(blocks.len() - 1)
        .zip(blocks.iter().skip(1))
        .map(|(start, end)| (*start, *end))
        .collect();

      ref_seq_intervals.push(intervals);
    }
  }
```

**Comment by CastilloDel** [comment]
I would like to give this one a try!

**Comment by brainstorm** [comment]
By all means, please go ahead! :)
