### ISSUE TITLE
Crypt4GH secrets manager

### ISSUE THREAD

**Issue by brainstorm** [umccr/htsget-rs#264]
Instead of providing static paths resolving to secrets/keys for Crypt4gh, it should point to an endpoint that resolves to a key management service/server (HSM, HTTP endpoint, GitHub `user.key`, etc...)... like [Elsa secrets provider](https://github.com/elsa-data/elsa-data/tree/dev/application/backend/src/config/providers) (focusing on those that run on the server side, such as AWS Secrets Manager and just file-based for dev) /cc @andrewpatto .

**Comment by brainstorm** [comment]
@mmalenic I believe you implemented most of this in https://github.com/umccr/htsget-rs/pull/271 ? ... not a custom API endpoint but perhaps it's good enough for now?

**Comment by mmalenic** [comment]
Yeah, it's probably okay for now. The Secrets Manager part is done, but the it's not customizable beyond that.

**Comment by brainstorm** [comment]
We can reopen once more complexity is needed then!
