### ISSUE TITLE
Implement BCF search backend (/variants endpoint)

### ISSUE THREAD

**Issue by brainstorm** [umccr/htsget-rs#33]
Since Noodles finished up its support relatively recently, its up for grabs:

https://github.com/zaeleus/noodles/issues/13

lower priority than the other formats and tasks though, since it's not used as much as `.vcf.gz`, but it would be great to have anyway for completeness and in-spec.

**Comment by CastilloDel** [comment]
I saw you assigned me this @brainstorm. If this is lower priority, should I work on #7 first? That one is assigned to you, but seems closely related with this one and I guess has higher priority. I will start looking for how to implement this, but feel free to notify me if I should work on #7

**Comment by CastilloDel** [comment]
That sounds really nice. Thank you!
