### ISSUE TITLE
htsget-http crate

### ISSUE THREAD

**Issue by brainstorm** [umccr/htsget-rs#36]
As with the [Go reference implementation](https://github.com/ga4gh/htsget-refserver/pull/24), there's a need for a separate crate in the workspace (htsget-http?) that serves requests, deals with JWT tokens, CORS, htsget tickets, etc...

**Comment by brainstorm** [comment]
Since this issue is very much coming up next soon after the good progress on formats that both Daniel and Marko have been pushing through, I think I'd be good to briefly discuss which Rust (local) web server frameworks/crates would be sensible to choose for our usecase. Reading through this post (which might be outdated because Rust is also fast in changing frameworks over one year):

https://www.lpalmieri.com/posts/2020-07-04-choosing-a-rust-web-framework-2020-edition/

I'd probably go with either `actix-web` or `warp` to provide serving of htsget requests... that being said I'd really like for this `htsget-http` crate to be a properly isolated shim/abstraction so that we can easily swap the http backend. This design goal is specially important because we aim to run this on lightweight AWS lambdas (https://github.com/awslabs/aws-lambda-rust-runtime/), so we might not even need to have Fargate nor Docker behind the scenes like we do today with [the current UMCCR htsget system architecture](https://github.com/umccr/infrastructure/tree/master/cdk/apps/htsget).

Opening the floor for some discussion about this with @chris-zen @victorskl @mmalenic @CastilloDel ;)

**Comment by CastilloDel** [comment]
Well, Rocket still hasn't released the 0.5 version, so if we are going to stick to stable rust that isn't an option.
`actix-web` seems to be the more mature of the other ones, although `warp` also seems good to me.
Looking at their crates.rs pages, [warp](https://crates.io/crates/warp) and [actix-web](https://crates.io/crates/actix-web) seem to be more used (~8.000 daily downloads) than [tide](https://crates.io/crates/tide)  (~1.500 daily downloads)

**Comment by victorskl** [comment]
(😅 Eek! you guys are so fast ironing out dealing with format there! 👏)

Thanks for pointers, Roman. Yep; I'll do "hello world" run to trial those web framework mention there. Then, give my feedback.

**Comment by chris-zen** [comment]
Hi, I think that all of them will be fine. What really matters to me is that they are not used to implement any kind of domain logic, just the glue code to adapt data between the HTTP REST protocol and the search service.

That said, I already have experience in real life with `actix-web`, and I could provide advice more easily. There is also the awesome [book from Luca Palmieri](https://www.zero2prod.com/assets/sample_zero2prod.pdf) for getting started. And if you know spanish, the amazing [videos from Roberto Huertas](https://www.youtube.com/watch?v=m0LuiS9squU&list=PLojDVPvSO1Di_QEnvDOI5FIeieqYpm1xd)

**Comment by CastilloDel** [comment]
I'm in the process of familiarizing myself with actix-web. The videos from Roberto Huertas are certainly good and the zero2prod book seems to cover lots of areas.

Apart from that, I have a question: should the htsget-http crate be directly executable or should it be a library to be called from another crate?

**Comment by brainstorm** [comment]
I'd say probably both? There should be a way to locally spawn an htsget-rs server for testing as the reference implementation does *and* have an API that exposes the endpoints so that it can be isolated and exchangeable?

**Comment by CastilloDel** [comment]
That makes sense. And it seems doable 👍🏻

**Comment by CastilloDel** [comment]
Okay, so I thought it was possible to declare dependencies only for a binary instead of the whole crate, but [it isn't](https://github.com/rust-lang/cargo/issues/1982). After knowing that, I think it will probably be better to have the http-htsget crate contain all the framework independent code and then have another crate (actix-htsget (?)) that contains the framework dependent code. That way it would be easily extensible and a user that only wants to use the library won't be forced to use actix_web as dependency.

**Comment by brainstorm** [comment]
Yep, that sounds good: an abstraction layer between specific http implementations and other crates like http-search.

**Comment by chris-zen** [comment]
My recommendation is to create different crates for different concerns. I would create the following crates:

- **htsget-search**: Library with the main logic to deal with the searches.
- **htsget-http-core**: Library with all the structs used to represent the htsget HTTP payloads including serde annotations
- **htsget-http-actix-web**: Binary with the specific code for actix-web. Referencing `htsget-http-core` & `htsget-search`.
- **htsget-http-aws-lambda**: Binary with the specific code for AWS Lambdas. Referencing `htsget-http-core` & `htsget-search`.

Please use `htsget-` as a prefix for all the crates.

**Comment by brainstorm** [comment]
I think that on our private conversations (via GA4GH's Slack), this was pretty much the plan we agreed upon. But please @CastilloDel, follow those exact naming conventions and his advice, Christian has good eye for those.

**Comment by CastilloDel** [comment]
Yes! I was using `htsget-http` and `htsget-actix`, but the naming convention proposed by @chris-zen seems better!

**Comment by CastilloDel** [comment]
@chris-zen I'm not really sure how to apply the dependency injection here. Could you share some ideas? You can look at the code I already have at #45

**Comment by chris-zen** [comment]
Hi @CastilloDel I'll do my best to find some time this weekend and have a look ;-)

**Comment by CastilloDel** [comment]
Thanks! I don't want to take you too much time, some ideas on how to do it should be enough.
