### ISSUE TITLE
Remove `file://`

### ISSUE THREAD

**Issue by CastilloDel** [umccr/htsget-rs#73]
To implement the benchmarks, we need to remove the `file://` scheme (which also isn't allowed by the htsget spec). See [here](https://github.com/umccr/htsget-rs/blob/ce002ef5ed4d97b2d721b89e73b34baa0d364625/htsget-search/src/storage/blocking/local.rs#L80). Last time I just changed it for `http://localhost`, but this time I was thinking maybe we should take a more permanent route? If I understand correctly, `LocalStorage` shouldn't be constrained to localhost.

**Comment by brainstorm** [comment]
Indeed, localstorage refers to an arbitrary amount of bytes on a volume, but the host of those volume(s) can be any host other than localhost too (connected to a network even). So yes, generalising it would be the best course of action.

**Comment by CastilloDel** [comment]
Okay! Sadly, I don't think I can commit the necessary time for this. Maybe Marko or you can take a look.

**Comment by brainstorm** [comment]
No worries @CastilloDel, thanks for pointing it out, we need to tackle this for sure if we want htsget-rs to be fully spec-compliant, which we do ;)
