### ISSUE TITLE
Append EOF for BAM and CRAM

### ISSUE THREAD

**Issue by brainstorm** [umccr/htsget-rs#85]
When returning the sliced data, those two formats are not hitting the client with the right EOF termination:

BAM: `1f 8b 08 04 00 00 00 00 00 ff 06 00 42 43 02 00 1b 00 03 00 00 00 00 00 00 00 00 00`
CRAM: `0f 00 00 00 ff ff ff ff 0f e0 45 4f 46 00 00 00 00 01 00 05 bd d9 4f 00 01 00 06 06 01 00 01 00 01 00 ee 63 01 4b`

Which leads to samtools (and most probably other clients) to error out accordingly:

```shell
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::bgzf_read_block] Invalid BGZF header at offset 4668
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
samtools view: error reading file "bam_slice.bam": No such process
samtools view: error closing "bam_slice.bam": -1
```

There are noodles methods that return this const EOF per format, use them.

Caveats:

1. Do not append EOF if request is header, only body.
1. Do not append EOF if request is whole file/object.

**Comment by mmalenic** [comment]
With LocalStorage, an EOF marker can be appended when retrieving the file, however I'm not sure how this should look with AwsS3Storage.

The AwsS3Storage returns presigned urls that correspond directly to S3 objects. Is there a way to edit these objects before they are dowloaded, or is the solution instead to make new, temporary s3 objects for that specific request?

**Comment by brainstorm** [comment]
Thanks @victorskl! @mmalenic , it seems that the EOF for that BAM got placed out of order, confusing Victor and some clients like samtools :-S

```hexdump
% echo 'H4sIBAAAAAAA/wYAQkMCABsAAwAAAAAAAAAAAA==' | base64 -d | hexdump -C
00000000  1f 8b 08 04 00 00 00 00  00 ff 06 00 42 43 02 00  |.........�..BC..|
00000010  1b 00 03 00 00 00 00 00  00 00 00 00              |............|
0000001c
```

In Victor’s example response, that base64 EOF should be placed last, AFAICT?:

```json
      {
        "url": "https://s3.ap-southeast-2.ama/<<SNIP__BREVITY>>PFM%3D",
        "headers": {
          "Range": "bytes=499249-574358"
        },
        "class": "body"
      },
      {
        "url": "data:;base64,H4sIBAAAAAAA/wYAQkMCABsAAwAAAAAAAAAAAA==",
        "headers": {},
        "class": "body"
      },
      {
        "url": "https://s3.ap-southeast-2.ama/<<SNIP__BREVITY>>xILPFM%3D",
        "headers": {
          "Range": "bytes=977196-996014"
        },
        "class": "body"
      }
    ]
  }
}
```

What could have affected the order?
