### ISSUE TITLE
Error response is missing htsget object

### ISSUE THREAD

**Issue by zaeleus** [umccr/htsget-rs#91]
Version: 75aed4760755a13d83e819fbcacbc77f40ee68b2

Error responses are missing the `htsget` container for the error object (see [_Htsget retrieval API spec v1.3.0_ § Errors](https://github.com/samtools/hts-specs/blob/d97f9e27b332e85eaebd9383f56a882ee3e11fc4/htsget.md#errors)).

#### Actual

`GET /reads/dne HTTP/1.1`

```json
{
    "error": "InvalidInput",
    "message": "Wrong key derived from ID: dne.bam"
}
```

#### Expected

```json
{
    "htsget": {
        "error": "InvalidInput",
        "message": "Wrong key derived from ID: dne.bam"
    }
}
```

**Comment by brainstorm** [comment]
Thanks for reporting @zaeleus, please do give it another spin ;)
