### ISSUE TITLE
Better CI and CD

### ISSUE THREAD

**Issue by brainstorm** [umccr/htsget-rs#97]
1. Fix caching mechanism on GHA, it currently takes too long and sometimes even times out: https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/
1. Implement continuous benchmarking: https://github.com/benchmark-action/github-action-benchmark

**Comment by brainstorm** [comment]
3. Also add CD to the mix with https://github.com/googleapis/release-please, or just copying the skeleton that Johannes uses for `rust-htslib`: https://github.com/rust-bio/rust-htslib/blob/master/.github/workflows/release-please.yml

Thanks @victorskl for the heads up on this, we definitely need proper release engineering on this project now that it's going to prod (https://crates.io, docker builds, binaries for different arches, doc generation, etc...).

**Comment by brainstorm** [comment]
As discussed with @mmalenic, we will experiment with https://www.conventionalcommits.org/en/v1.0.0/ and suitable integrations so that we can easily generate changelogs in releases.

**Comment by brainstorm** [comment]
More goodies on the benchmarking side: 

https://www.tweag.io/blog/2022-03-03-criterion-rs/
https://github.com/BurntSushi/critcmp

I'm looking at some system that could keep historical benchmarking data in order to detect regressions and performance improvements, automatically (if something else than benchmark-action came up in the last 5 months).

**Comment by mmalenic** [comment]
It seems like [benchmark-action](https://github.com/benchmark-action/github-action-benchmark) is still the most well supported. I think this action does store previous data which you can visualise in graphs.

**Comment by brainstorm** [comment]
> It seems like [benchmark-action](https://github.com/benchmark-action/github-action-benchmark) still has the best features. This action does store previous data which you can visualise in graphs such as the one you linked.

Indeed, basing my current iteration off of it, just wanted to see what's out there, this action still seems to be the best so far.

**Comment by mmalenic** [comment]
> As discussed with @mmalenic, we will experiment with https://www.conventionalcommits.org/en/v1.0.0/ and suitable integrations so that we can easily generate changelogs in releases.

I'm happy to be pretty flexible about these. I notice that some projects tend to avoid the predefined types, and instead just make the type the scope of the change. E.g. [tokio-rs](https://github.com/tokio-rs/tokio/commits/master).

I'm not sure how types like `feat` interact with a larger PR that might be working towards one feature, but should be split up into multiple commits. Should each commit have `feat` in front of it?

**Comment by brainstorm** [comment]
> > As discussed with @mmalenic, we will experiment with https://www.conventionalcommits.org/en/v1.0.0/ and suitable integrations so that we can easily generate changelogs in releases.
> 
> I'm happy to be pretty flexible about these. I notice that some projects tend to avoid the predefined types, and instead just make the type the scope of the change. E.g. [tokio-rs](https://github.com/tokio-rs/tokio/commits/master).
> 
> I'm not sure how types like `feat` interact with a larger PR that might be working towards one feature, but should be split up into multiple commits. Should each commit have `feat` in front of it?

I still haven't research the GHA for conventional commits... I would base our way of writing the commits on the features available on those, i.e:

https://github.com/marketplace/actions/changelog-from-conventional-commits

I'd like to prioritize automation over our own conventions first. Pretty much like git and nvie workflows: stick to third party conventions first to avoid cognitive burden and then adapt to our needs if that shirt doesn't fit us?

**Comment by mmalenic** [comment]
Yeah agreed, we should just do what others do I think.

**Comment by brainstorm** [comment]
Benchmarks now available on those two locations:

https://umccr.github.io/htsget-rs/dev/bench/
https://umccr.github.io/htsget-rs/dev/bench/native/criterion/reports/

A few things to polish w.r.t history keeping, displaying results, routes, add 3rd party projects for comparison, etc... but at least it's up and running now.

Also PRs upstream need to be reviewed and merged, so using [my own fork for now](https://github.com/benchmark-action/github-action-benchmark):

https://github.com/benchmark-action/github-action-benchmark/pull/145
https://github.com/benchmark-action/github-action-benchmark/pull/146

**Comment by brainstorm** [comment]
This is awesome: https://www.jibbow.com/posts/criterion-flamegraphs/
